#  Code for 2D staggered Lagrangian method in Cartersian coordinates

## Control equations

一般形式下，弹塑性流体控制方程为：

质量方程：
\begin{equation}
  \frac{dm}{dt}=0
  \end{equation}
动量方程：
\begin{equation}
  \frac{d\rho \mathbf{u}}{dt}= \nabla \cdot  \mathbf{\Pi} 
\end{equation}

能量方程：
\begin{equation}
 \rho \frac{de}{dt}= \mathbf{\sigma} \cdot \mathbf{\varepsilon}
\end{equation}

\section{二维控制方程}

运动方程：
\begin{equation}
  \frac{d(r,z)}{dt}=(u,v)
\end{equation}

质量守恒：
\begin{equation}\label{eq:38}
  \frac{dm}{dt}=0
\end{equation}

动量守恒方程：
\begin{equation}\label{eq:3}
  \begin{array}{l}
	\displaystyle \rho \frac{du}{dt}=\frac{\partial \sigma _{rr}}{\partial r}+ \frac{\partial s_{rz}}{\partial z}\\[0.3cm]
  \displaystyle \rho \frac{dv}{dt}=\frac{\partial \sigma _{zz}}{\partial z}+ \frac{\partial s_{rz}}{\partial r}\\
  \end{array}
  \end{equation}

能量守恒方程：
\begin{equation}
  \begin{array}{l}
	\displaystyle \rho \frac{de}{dt}=\sigma _{rr}\frac{\partial u}{\partial r}+\sigma_{zz}\frac{\partial v}{\partial z}+s_{rz}\left( \frac{\partial u}{\partial z}+\frac{\partial v}{\partial r}\right)\\[0.3cm]
	\displaystyle = -p\frac{dV}{dt}+ s_{rr}\frac{\partial u}{\partial r}+s_{zz}\frac{\partial v}{\partial z}+s_{rz}\left( \frac{\partial u}{\partial z}+\frac{\partial v}{\partial r}\right)\\
	\end{array}
	\end{equation}

本构方程：
\begin{equation}
  \begin{array}{l}
	\displaystyle \frac{ds_{rr}}{dt}=2\mu \left(\frac{\partial u}{\partial r}-\frac{1}{3}\nabla \cdot \vec{u} \right) +s_{rz}\left(\frac{\partial u}{\partial z}-\frac{\partial v}{\partial r}\right)\\[0.3cm]
	\displaystyle \frac{ds_{zz}}{dt}=2\mu \left(\frac{\partial v}{\partial z}-\frac{1}{3}\nabla \cdot \vec{u} \right) -s_{rz}\left(\frac{\partial u}{\partial z}-\frac{\partial v}{\partial r}\right)\\[0.3cm]
	\displaystyle \frac{ds_{rz}}{dt}=\mu \left(\frac{\partial u}{\partial r}+\frac{\partial v}{\partial z}\right) + \frac{s_{rr}-s_{zz}}{2}\left(\frac{\partial u}{\partial z}-\frac{\partial v}{\partial r}\right)\\
  \end{array}
  \end{equation}

Von Mises屈服条件：
\begin{equation}
  \frac{3}{2}(s_{rr}^2+s_{zz}^2+s_{\theta \theta}^2+2s_{xy}^2)\le (Y^0)^2
\end{equation}







$$ s_{\theta\theta} = - (s_{rr} +s_{zz}) $$

一般形式下，弹塑性流体控制方程为：

质量方程：
\begin{equation}
  \frac{dm}{dt}=0
  \end{equation}
动量方程：
\begin{equation}
  \frac{d\rho \mathbf{u}}{dt}= \nabla \cdot  \mathbf{\Pi} 
\end{equation}

能量方程：
\begin{equation}
 \rho \frac{de}{dt}= \mathbf{\sigma} \cdot \mathbf{\varepsilon}
\end{equation}

\section{二维控制方程}

运动方程：
\begin{equation}
  \frac{d(r,z)}{dt}=(u,v)
\end{equation}

质量守恒：
\begin{equation}\label{eq:38}
  \frac{dm}{dt}=0
\end{equation}

动量守恒方程：
\begin{equation}\label{eq:3}
  \begin{array}{l}
	\displaystyle \rho \frac{du}{dt}=\frac{\partial \sigma _{rr}}{\partial r}+ \frac{\partial s_{rz}}{\partial z}\\[0.3cm]
  \displaystyle \rho \frac{dv}{dt}=\frac{\partial \sigma _{zz}}{\partial z}+ \frac{\partial s_{rz}}{\partial r}\\
  \end{array}
  \end{equation}

能量守恒方程：
\begin{equation}
  \begin{array}{l}
	\displaystyle \rho \frac{de}{dt}=\sigma _{rr}\frac{\partial u}{\partial r}+\sigma_{zz}\frac{\partial v}{\partial z}+s_{rz}\left( \frac{\partial u}{\partial z}+\frac{\partial v}{\partial r}\right)\\[0.3cm]
	\displaystyle = -p\frac{dV}{dt}+ s_{rr}\frac{\partial u}{\partial r}+s_{zz}\frac{\partial v}{\partial z}+s_{rz}\left( \frac{\partial u}{\partial z}+\frac{\partial v}{\partial r}\right)\\
	\end{array}
	\end{equation}

本构方程：
\begin{equation}
  \begin{array}{l}
	\displaystyle \frac{ds_{rr}}{dt}=2\mu \left(\frac{\partial u}{\partial r}-\frac{1}{3}\nabla \cdot \vec{u} \right) +s_{rz}\left(\frac{\partial u}{\partial z}-\frac{\partial v}{\partial r}\right)\\[0.3cm]
	\displaystyle \frac{ds_{zz}}{dt}=2\mu \left(\frac{\partial v}{\partial z}-\frac{1}{3}\nabla \cdot \vec{u} \right) -s_{rz}\left(\frac{\partial u}{\partial z}-\frac{\partial v}{\partial r}\right)\\[0.3cm]
	\displaystyle \frac{ds_{rz}}{dt}=\mu \left(\frac{\partial u}{\partial r}+\frac{\partial v}{\partial z}\right) + \frac{s_{rr}-s_{zz}}{2}\left(\frac{\partial u}{\partial z}-\frac{\partial v}{\partial r}\right)\\
  \end{array}
  \end{equation}

Von Mises屈服条件：
\begin{equation}
  \frac{3}{2}(s_{rr}^2+s_{zz}^2+s_{\theta \theta}^2+2s_{xy}^2)\le (Y^0)^2
\end{equation}







## Compatible Staggered Discretization

<img src="Grid.png" width = "800" height = "400" div align=center /> 

<img src="cellpoint.png" width = "800" height = "400" div align=center />

### Quatities:

On point: ($x_p$,$y_p$), ($u_p$,$v_p$)

Zonal:  $V_z$, $\rho_z$, $m_z$, $e_z$, $p_z$

By the relation 
$$\frac{dm_z}{dt} =0$$
we have 
$$\rho_z(t) = m_z/V_z(t)$$

Also 
$$d(x_p)/dt = u_p, \quad d(y_p)/dt = v_p$$

In [10]:
struct Const
    Y0 ::Float64 #Yielding strength
    ρ0 ::Float64 
    Γ0 ::Float64
    μ  ::Float64
    a0 ::Float64
    s0 ::Float64
end


In [11]:
mutable struct Var
    r::Array{Float64,1}
    z::Array{Float64,1}
    u::Array{Float64,1}
    v::Array{Float64,1}
    ρ::Array{Float64,1}
    p::Array{Float64,1}
    σ::Array{Float64,2} # σ[1] = σrr σ[2] = σzz σ[3] = σrz
end    

In [12]:
struct prb
    tt::Float64
    sf::Float64
end

### Point mass 

Point mass $m_p$ is used to solve point momentum $\mu_p = m_p \bf{u}_p$ and kinetic energy $K_p = m_p \frac{\bf{u}_p^2}{2}$

<img src="Ins.jpg" width = "200" height = "400" div align=center /> 

$$m_p = \sum_{z\in Z(p)} A_z^p \rho^p_z$$

$$\rho_z(t) = m_z/V_z(t)$$

In [13]:
function MassAndDens(mz::Array{Float64,1},x::Array{Float64,1},y::Array{Float64,1})
    
    Ic, = size(mz)
    Ip, = size(Tc)
    Asbz = zeros(Float64,4)
    ρ = zeros(Float64,Ic)
    mp = zeros(Float64,Ip)
    xz = zeros(Float64,4)
    yz = zeros(Float64,4)
    for i in 1:Ic
        xz[1:4] = x[Tp[i,1:4]]
        yz[1:4] = y[Tp[i,1:4]]
        Asbz = A_z(xz,yz)
        Az = sum(Asbz)
        ρ[i] = mz[i]/Az
        
        for j = 1:4
            ip = Tp[i,j]
            mp[ip] = mp[ip] + Asbz[j]*ρ[i]
        end
    end
   # @show mp
    return ρ,mp   
end

MassAndDens (generic function with 1 method)


$$ A_z^1 = \frac{5A_{41}+5A_{12}+A_{23}+A_{34}}{12}$$
$$ A_z^2 = \frac{A_{41}+5A_{12}+5A_{23}+A_{34}}{12}$$
$$ A_z^3 = \frac{A_{41}+A_{12}+5A_{23}+5A_{34}}{12}$$
$$ A_z^4 = \frac{5A_{41}+A_{12}+A_{23}+5A_{34}}{12}$$

In [14]:
function A_z(xz::Array{Float64,1},yz::Array{Float64,1}) 
    A =zeros(Float64,4)
    xc= sum(xz[i] for i in 1:4)/4
    yc= sum(yz[i] for i in 1:4)/4
    
    A41 = Area3(xz[4],xz[1],xc,yz[4],yz[1],yc)
    A12 = Area3(xz[1],xz[2],xc,yz[1],yz[2],yc)
    A23 = Area3(xz[2],xz[3],xc,yz[2],yz[3],yc)
    A34 = Area3(xz[3],xz[4],xc,yz[3],yz[4],yc)

    A[1] = (5A41+5A12+A23+A34)/12
    A[2] = (A41+5A12+5A23+A34)/12
    A[3] = (A41+A12+5A23+5A34)/12
    A[4] = (5A41+A12+A23+5A34)/12
    
#    A[1] = (A41+A12+A23+A34)/4
#    A[2] = (A41+A12+A23+A34)/4
#    A[3] = (A41+A12+A23+A34)/4
#    A[4] = (A41+A12+A23+A34)/4
    
    return A
end

A_z (generic function with 1 method)

<img src="n12.png" width = "300" height = "300" div align=center />

$$\overrightarrow{n}_{12} = \frac{1}{L_{12}}(y_2- y_1, x_1-x_2)  $$

$$\overrightarrow{\tau}_{12} = \frac{1}{L_{12}}(x_2- x_1, y_2-y_1)  $$

$$ \mathbf{F_1}  = \frac{1}{2}  \left[ -\sigma_{rr}(z_2-z_4)+ s_{rz}(r_2 -r_4), \sigma_{zz}(r_2-r_4) +s_{rz}(z_4 -z_2) , \right] $$ 

In [15]:
function force_zone(x,y,u,v,ρ,p,σ) #(r,z)
   
    Fx = zeros(Float64,4)
    Fy = zeros(Float64,4)
    
    
    Fx[1] = 0.5(σ[1]*(y[4] - y[2]) + σ[3]*(x[2] - x[4]))
    Fy[1] = 0.5(σ[3]*(y[4] - y[2]) + σ[2]*(x[2] - x[4]))
    
    Fx[2] = 0.5(σ[1]*(y[1] - y[3]) + σ[3]*(x[3] - x[1]))
    Fy[2] = 0.5(σ[3]*(y[1] - y[3]) + σ[2]*(x[3] - x[1]))
    
    Fx[3] = 0.5(σ[1]*(y[2] - y[4]) + σ[3]*(x[4] - x[2]))
    Fy[3] = 0.5(σ[3]*(y[2] - y[4]) + σ[2]*(x[4] - x[2]))
    
    Fx[4] = 0.5(σ[1]*(y[3] - y[1]) + σ[3]*(x[1] - x[3]))
    Fy[4] = 0.5(σ[3]*(y[3] - y[1]) + σ[2]*(x[1] - x[3]))
      
    ex,ey = hourglass_viscosity(x, y, u, v, ρ, p,σ) 
  #  ex .= 0
    Fx = Fx .+ ex
    Fy = Fy .+ ey
    
    return Fx,Fy
end           

force_zone (generic function with 1 method)

\begin{equation}
  \begin{aligned}
	&\displaystyle \rho \frac{de}{dt}= \mathbf{\sigma} \cdot \mathbf{\varepsilon}\\ 
	&=
	\sigma _{rr}\frac{\partial u}{\partial r}+\sigma_{zz}\frac{\partial v}{\partial z}+\sigma_{rz}\left( \frac{\partial u}{\partial z}+\frac{\partial v}{\partial r}\right)
	\end{aligned}
	\end{equation}
    
\begin{equation}
  \begin{aligned}
	&\displaystyle M \frac{de}{dt}=  
\int_{\Omega} \sigma _{rr}\frac{\partial u}{\partial r}+\sigma_{zz}\frac{\partial v}{\partial z}+\sigma_{rz}\left( \frac{\partial u}{\partial z}+\frac{\partial v}{\partial r}\right)d\Omega
	\end{aligned}
	\end{equation}


\begin{equation}
  \begin{aligned}
\int_{\Omega}  \frac{\partial u}{\partial r} d\Omega&=  -\oint_{\partial \omega}u dz\\
  &= \frac{1}{2} \left((u_1-u_3)(z_2-z_4)+(u_2-u_4)(z_3-z_1)\right)
  \end{aligned}
\end{equation}

\begin{equation}
  \begin{aligned}
\int_{\Omega}  \frac{\partial u}{\partial z} d\Omega&= \oint_{\partial \omega}u dy\\
  &= -\frac{1}{2} \left((u_1-u_3)(r_2-r_4)+(u_2-u_4)(r_3-r_1)\right)
  \end{aligned}
\end{equation}

$$ \frac{\partial u}{\partial x}  \approx \frac{1}{2A}((u_1-u_3)(y_2-y_4)+(u_2-u_4)(-y_1+y_3))$$ 

$$ \frac{\partial v}{\partial y}  \approx -\frac{1}{2A}((v_1-v_3)(x_2-x_4)+(v_2-v_4)(-x_1+x_3))$$ 

对于节点
$$ \rho \frac{d \mathbf{u}}{dt} = - \nabla p$$

$$m_p \frac{d\bf{u}_p}{dt} = \sum_{p\in P(z)} \bf{F}_z^p$$

$$F_z^1 = \mathbf{F}_1 + c\mathbf{e}_1$$

本构方程：
\begin{equation}
  \begin{array}{l}
	\displaystyle \frac{ds_{rr}}{dt}=2\mu \left(\frac{\partial u}{\partial r}-\frac{1}{3}\nabla \cdot \vec{u} \right) +s_{rz}\left(\frac{\partial u}{\partial z}-\frac{\partial v}{\partial r}\right)\\[0.3cm]
	\displaystyle \frac{ds_{zz}}{dt}=2\mu \left(\frac{\partial v}{\partial z}-\frac{1}{3}\nabla \cdot \vec{u} \right) -s_{rz}\left(\frac{\partial u}{\partial z}-\frac{\partial v}{\partial r}\right)\\[0.3cm]
	\displaystyle \frac{ds_{rz}}{dt}=\mu \left(\frac{\partial u}{\partial z}+\frac{\partial v}{\partial r}\right) - \frac{s_{rr}-s_{zz}}{2}\left(\frac{\partial u}{\partial z}-\frac{\partial v}{\partial r}\right)\\
  \end{array}
  \end{equation}

Von Mises屈服条件：
\begin{equation}
  \frac{3}{2}(s_{rr}^2+s_{zz}^2+s_{\theta \theta}^2+2s_{xy}^2)\le (Y^0)^2
\end{equation}


In [16]:
function rhs(var::Var)
    μ = con1.μ
    r,z,u,v,ρ,p,σ = var.r,var.z,var.u,var.v,var.ρ,var.p,var.σ
    
    Ic, = size(Tp)
    Ip, = size(Tc)
    rhsu = zeros(Float64,Ip)
    rhsv = zeros(Float64,Ip) 
    rhse = zeros(Float64,Ic)
    rhss = zeros(Float64,Ic,3)
    
    rcell = zeros(Float64,4)
    zcell = zeros(Float64,4)
    ucell = zeros(Float64,4)
    vcell = zeros(Float64,4)
    for i in 1:Ic
        for j =1:4
            rcell[j] = r[Tp[i,j]]
            zcell[j] = z[Tp[i,j]]
            ucell[j] = u[Tp[i,j]]
            vcell[j] = v[Tp[i,j]]
        end
        Az = sum(A_z(rcell,zcell))
        Fx,Fy = force_zone(rcell,zcell,ucell,vcell,ρ[i],p[i],σ[i,1:3])   
       # @show Fx
        ∂u_∂r,∂u_∂z = ∂uv(rcell,zcell, ucell)
        ∂v_∂r,∂v_∂z = ∂uv(rcell,zcell, vcell)
        rhse[i] = σ[i,1]*∂u_∂r + σ[i,2]*∂v_∂z+σ[i,3]*(∂u_∂z + ∂v_∂r)
        for j = 1:4
            ip = Tp[i,j]
            rhsu[ip] +=  Fx[j]
            rhsv[ip] +=  Fy[j]
        end  
        ∇u = ∂u_∂r + ∂v_∂z
    
        rhss[i,1] =  (2μ*(2/3*∂u_∂r - 1/3*∂v_∂z) + σ[i,3]*(∂u_∂z - ∂v_∂r)) ./Az
        rhss[i,2] =  (2μ*(2/3*∂v_∂z - 1/3*∂u_∂r) - σ[i,3]*(∂u_∂z - ∂v_∂r)) ./Az
        rhss[i,3] =   (μ*(∂u_∂z+∂v_∂r)  -   (σ[i,1] - σ[i,2])*(∂u_∂z - ∂v_∂r)) ./Az     
    #    @show rhsu 
    end
    
    return rhse, rhsu,rhsv,rhss

end     

rhs (generic function with 1 method)

$$ \mathbf{S} = \mathbf{S} \times \text{min} \left(1,Y_0/\sqrt{\frac{3}{2}\mathbf{S}:\mathbf{S}}\right)$$

In [17]:
function yield_s!(s,con)
    Y0 = con.Y0
    I, = size(s)
    for i in 1:I
        for j = 1:3
        sums = s[i,1]^2 +s[i,2]^2 +2*s[i,3]^2 +(s[i,1]+s[i,2])^2
        s[i,j] = s[i,j] * min(1,Y0/√(3/2*sums))
            end 
    end
    return s
end

yield_s! (generic function with 1 method)

In [18]:
function predictor_corrector2nd(dt,var::Var,mz)
    r,z,u,v,ρ,p,σ = var.r,var.z,var.u,var.v,var.ρ,var.p,var.σ
    
    Ip, = size(u)
    Ic, = size(p)
    
    ρ,mp = MassAndDens(mz,r,z)
    e = p_to_e(ρ, p,con1)  
    p = artificial_viscosity!(r,z,u,v,ρ,p)
    s = zeros(Float64,Ic,3)
    
    p = e_to_p(ρ, e, con1)
 #   @show p "predictor"
   
                
    s[:,1] = σ[:,1] .+ p[:]
    s[:,2] = σ[:,2] .+ p[:]
    s[:,3] = σ[:,3]
    
    rhse, rhsu,rhsv,rhss = rhs(var)
   
    rhsu,rhsv = Bound(rhsu,rhsv,var)
 #    @show rhsu
    r₀ =  r + dt*u
    z₀  = z + dt*v
    u₀  = u + dt*(rhsu ./ mp)
    v₀  = v + dt*(rhsv ./ mp)
    e₀  = e + dt*(rhse ./ mz) 
    s₀  = s + dt*rhss
  #  @show rhsu
    s₀ = yield_s!(s₀,con1)
    
    ρ,mp = MassAndDens(mz,r₀,z₀)
    p = e_to_p(ρ,e₀,con1)
    
    p = artificial_viscosity!(r₀,z₀,u₀,v₀,ρ,p) 
    
    σ[:,1] = s₀[:,1] .- p[:]
    σ[:,2] = s₀[:,2] .- p[:]
    σ[:,3] = s₀[:,3]
    var = Var(r₀, z₀, u₀, v₀, ρ, p, σ)
    rhse₀,rhsu₀,rhsv₀,rhss₀ = rhs(var)
   #  @show u₀,rhsu₀
    rhsu₀,rhsv₀ = Bound(rhsu₀,rhsv₀,var)
  #  @show s[:,1]
    r +=  0.5dt*(u + u₀)
    z +=  0.5dt*(v + v₀)
    u +=  0.5dt*(rhsu + rhsu₀) ./ mp
    v +=  0.5dt*(rhsv + rhsv₀) ./ mp
    e +=  0.5dt*(rhse + rhse₀) ./ mz
    s  += 0.5dt*(rhss + rhss₀)
    
    s = yield_s!(s,con1)
    
    ρ,mp = MassAndDens(mz,r,z)
    p = e_to_p(ρ,e,con1) 
    σ[:,1] = s[:,1] .- p[:]
    σ[:,2] = s[:,2] .- p[:]
    σ[:,3] = s[:,3]
    
    var = Var(r,z,u,v,ρ,p,σ) 
    return var
end

predictor_corrector2nd (generic function with 1 method)

In [19]:
var,mz,I,J = Collapse()
var = TimeSolve(var,mz)

UndefVarError: UndefVarError: Area3 not defined

In [20]:
function fη(ρ,c::Const)
    η = ρ/c.ρ0
    fη=(η .-1.0) .* (η .-c.Γ0*(η .-1.0)/2.0) ./ (η .-c.s0*(η .-1)) .^2
end

function fηη(ρ,c::Const)
    η = ρ/c.ρ0
    fηη=(η .+(c.s0-c.Γ0) .* (η .-1)) ./(η .-c.s0*(η .- 1)) .^3
end

fηη (generic function with 1 method)

In [21]:
function Euler1st(dt,mz,p,var::Var)
    r,z,u,v,ρ,σ = var.r,var.z,var.u,var.v,var.ρ,var.σ
    Ip, = size(u)
    Ic, = size(p)
    
    ρ,mp = MassAndDens(mz,r,z)
  
     e = p_to_e(p, ρ,con1)
     
     p = artificial_viscosity!(p,var)
        
     σ[:,1] = s[:,1] .- p[:]
     σ[:,2] = s[:,2] .- p[:]
     σ[:,3] = s[:,3]
    
     rhse, rhsu,rhsv,rhss = Rhs(r,z,u, v,ρ, σ)
    
     rhsu,rhsv = Bound(rhsu,rhsv,r,z,u, v,ρ, p)
    
    x  +=  dt*u
    y  +=  dt*v
    u  += dt*(rhsu ./ mp)
    v  += dt*(rhsv ./ mp)
    e  += dt*(rhse ./ mz)
    s  += dt*(rhss ./ mz)

    ρ,mp = MassAndDens(mz,r,z)
    
    p = eTop(e, ρ,con1)

    return u,v,x,y,p,ρ
end


Euler1st (generic function with 1 method)

In [22]:
function Bound(rhsu,rhsv,var)
    Ip, = size(Tc)
    Ib, = size(Tb)
   
    r,z,u,v,ρ,p,σ = var.r,var.z,var.u,var.v,var.ρ,var.p,var.σ
    rcell = zeros(Float64,4)
    zcell = zeros(Float64,4)
    ucell = zeros(Float64,4)
    vcell = zeros(Float64,4)
    ip1 = zeros(Int,4)
    
    for i in 1:Ib
        ic = Tb[i,1]        
        rcell[1:4] = r[Tp[ic,1:4]]
        zcell[1:4] = z[Tp[ic,1:4]]
        ucell[1:4] = u[Tp[ic,1:4]]
        vcell[1:4] = v[Tp[ic,1:4]]
          
        ex,ey = hourglass_viscosity(rcell, zcell, ucell, vcell, ρ[ic]
                                    , p[ic],σ[ic,:])
        i₁ = Tb[i,2]
        i₂ = i₁+1
        if i₁ == 4
            i₂ = 1
        end
        nx = y[i₂] -y[i₁]
        ny = x[i₁] -x[i₂]
        for j in (i₁,i₂)
            Fx = -σ[ic,1]*nx/2 -σ[ic,3]*ny/2+ex[j]*nx^2/(nx^2+ny^2) 
            Fy = -σ[ic,3]*nx/2 -σ[ic,2]*ny/2+ey[j]*nx^2/(nx^2+ny^2)
            ip = Tp[ic,j]
            rhsu[ip] -= Fx
            rhsv[ip] -= Fy
            
        end
        ip = Tp[ic,i₁]
        if Tb[i,3] == 2 # boundary
            u[ip] = u[ip]*ny^2/(nx^2 +ny^2)
            v[ip] = v[ip]*nx^2/(nx^2 +ny^2)
        end
        
    end 
    return rhsu, rhsv
end  

Bound (generic function with 1 method)

### Boundary force

If one edge of a cell is a free boundary, then $f$ on the points is zero. As we have add it in RHs(), we need to remove it by resolve it again. Different from RHs(), at every point of a cell the force is composited by two parts on different edges. This is distinguished by $k$ when $k = 1$ the boundary is on y direction, forces on 12 and 34 boundary must be subtracted. When $ k =2$ the boundary is on x direction, subtract forces on 41, 23. 

In [23]:
function F_zB(x,y,u,v,ρ,p,σ,j::Int,k::Int)
    Fx = 0.0
    Fy = 0.0      
    
    ex,ey = hourglass_viscosity(x, y, u, v, ρ, p,σ)
    
    if k==1 # y direction 
     #   L12 = √((x[2]-x[1])^2+(y[2]-y[1])^2)
        n12x = y[2]-y[1]
        n12y = -x[2]+x[1]
     #   L34 = √((x[4]-x[3])^2+(y[4]-y[3])^2)
        n34x = y[4]-y[3]
        n34y = -x[4]+x[3]
        if j == 1  #Point 1
            Fx = -σ[1]*n12x/2 -σ[3]*n12y/2
            Fy = -σ[3]*n12x/2 -σ[2]*n12y/2 + ey[1]
        elseif j == 2 
             Fx = -σ[1]*n12x/2 -σ[3]*n12y/2
             Fy = -σ[3]*n12x/2 -σ[2]*n12y/2+ ey[2]
        elseif j == 3
            Fx = -σ[1]*n34x/2  -σ[3]*n34y/2
            Fy = -σ[3]*n34x/2  -σ[2]*n34y/2 + ey[3]
        else 
            Fx = -σ[1]*n34x/2  -σ[3]*n34y/2
            Fy = -σ[3]*n34x/2  -σ[2]*n34y/2 + ey[4]
        end
    elseif k == 2
      #  L41 = √((x[1]-x[4])^2+(y[1]-y[4])^2)
        n41x = y[1]-y[4]
        n41y =  -x[1]+x[4]

       # L23 = √((x[3]-x[2])^2+(y[3]-y[2])^2)
        n23x = y[3]-y[2]
        n23y = -x[3]+x[2]
        if j == 1
            Fx = -σ[1]*n41x/2 -σ[3]*n41y/2 + ex[1]
            Fy = -σ[3]*n41x/2 -σ[2]*n41y/2 
        elseif j == 4 
            Fx = -σ[1]*n41x/2 -σ[3]*n41y/2 + ex[4]
            Fy = -σ[3]*n41x/2 -σ[2]*n41y/2 
        elseif j == 3
            Fx = -σ[1]*n23x/2 -σ[3]*n23y/2+ ex[3]
            Fy =  -σ[3]*n23x/2 -σ[2]*n23y/2
        else 
           Fx = -σ[1]*n23x/2 -σ[3]*n23y/2+ ex[2]
            Fy =  -σ[3]*n23x/2 -σ[2]*n23y/2
        end
    end
    return Fx,Fy
    end           

F_zB (generic function with 1 method)

### EOS 
$$ e = \frac{p}{(\gamma-1)\rho}$$

In [24]:
function p_to_e(ρ,p,con)
    c=con
    ei = (p .- c.ρ0*c.a0^2*fη(ρ,c))/(c.ρ0*c.Γ0)
    return ei
end
function e_to_p(ρ,ei,con::Const)
    c=con
    p = c.ρ0*c.Γ0*ei .+ c.ρ0*c.a0^2*fη(ρ,c)
    return p
end

e_to_p (generic function with 1 method)

In [25]:
function CFL(SF,var)
    r,z,u,v,ρ,p,σ = var.r,var.z,var.u,var.v,var.ρ,var.p,var.σ
    Ic, = size(ρ)
    cflmin = 1.e9
      cfl = 0 
    for i in 1:Ic
        cfl =0
        u2max = 0
        u2=0.0
        for j = 1:4
            ip = Tp[i,j]
            u2 = u[ip]^2+v[ip]^2
            if u2 > u2max ; u2max = u2; end
        end
        
        dlmin = (r[Tp[i,4]] - r[Tp[i,1]])^2+(z[Tp[i,4]]-z[Tp[i,1]])^2
       
        for j=1:3
            dl= (r[Tp[i,j+1]] - r[Tp[i,j]])^2+(z[Tp[i,j+1]]-z[Tp[i,j]])^2
            if dl < dlmin; dlmin=dl; end
        end
        c = sound([ρ[i],u[i],p[i],min(σ[i,1]+p[i],σ[i,2]+p[i])],con1)
        cfl = √(dlmin)/(√(u2max)+c)
        if cfl < cflmin; cflmin = cfl; end
    end
 #   @show cflmin
    dt = cflmin*SF
    return dt
end 
        

CFL (generic function with 1 method)

In [26]:
function sound(uo::Array{Float64,1},con::Const,EoP::Int=1)
    a0,ρ0,Γ0,Y0,μ  = con.a0,con.ρ0,con.Γ0,con.Y0,con.μ
    ρ,uu,p,sxx   = uo[1:4]
    a2  = a0^2*fηη(ρ,con)+p/ρ^2*ρ0*Γ0
    if EoP == 2
        c=sqrt(a2-ρ0/ρ^2*Γ0*sxx)
        return c
    else
       #  @show a2,ρ0/ρ^2,4.0/3*μ/ρ
        c=sqrt(a2-ρ0/ρ^2*Γ0*sxx+4.0/3*μ/ρ)
       
        return c
    end
end

sound (generic function with 2 methods)

In [27]:
function TimeSolve(var,mz)
    tt= problem.tt
    sf =problem.sf
    t= 0.0
    t₁ = tt/100
    t₂ = t₁
    while t<tt   
#for i in 1:50
        dt=CFL(sf,var)
   #     @show dt
        if t+dt>tt
           dt = tt-t
        end
        
        var = predictor_corrector2nd(dt,var,mz)
        t += dt
        if t > t₁
            println(t)
            t₁ += t₂
        end
    end
    return var
end

TimeSolve (generic function with 1 method)

## Artificial Viscosity 

Use the strain rate to construct the artificial viscosity 
$$\frac{ds}{dt} = \frac{\partial u}{\partial x}  + \frac{\partial v}{\partial y} $$


Then the artificial viscosity can be written as
$$ q_w = \left\{ \begin{align}
\alpha L \rho \left( \frac{ds}{dt} \right)^2 +  \beta L^2 \rho c \left|\frac{ds}{dt}\right|, \quad \text{if}  \quad \frac{ds}{dt}< 0,\\
0, \quad \text{if} \quad \frac{ds}{dt}\ge 0. \\
\end{align}
\right.
$$
where $\alpha = 0.6$, $\beta = 2.0 $ and $c$ is the sonic speed.

$L$ is the reference length, and constructed as
$$L = A/L_{\text{max}} $$

$$L_{\text{max}} = \text{max}(L_{13},L_{24})$$


In [28]:
function artificial_viscosity_c!(x,y,u,v,ρ,p)
    xc = sum(x[i] for i in 1:4)/4
    yc = sum(y[i] for i in 1:4)/4
    
    ∂u_∂x,tmp = ∂uv(x,y,u)
    tmp,∂v_∂y = ∂uv(x,y,v)
    c = sound([ρ,0.0,p,0.0],con1)
    Lmax = max(√((x[3] - x[1])^2+(y[3] - y[1])^2) ,√((x[2] - x[4])^2+(y[2] - y[4])^2) )  
    A = area_quadrangle(x, y)
    L = A/Lmax 

    if ∂u_∂x + ∂v_∂y> 0
        q = 0
    else
        q = 0.6ρ*L*c*(abs(∂u_∂x+∂v_∂y))/A +2.0L^2*ρ*((∂u_∂x+∂v_∂y)^2)/A^2 
    end
    return p+q
end

artificial_viscosity_c! (generic function with 1 method)

$$b_2 \rho Lc \frac{\partial u}{\partial x} - b_{12}\rho L^2 \left(\frac{\partial u}{\partial x}\right)^2$$

In [29]:
function artificial_viscosity!(r,z,u,v,ρ,p)
    I, = size(Tp)
    rcell = zeros(Float64,4)
    zcell = zeros(Float64,4)
    ucell = zeros(Float64,4)
    vcell = zeros(Float64,4)
   
    for i in 1:I
        for j in 1:4
            ip = Tp[i,j]
            rcell[j] = r[ip]
            zcell[j] = z[ip]
            ucell[j] = u[ip]
            vcell[j] = v[ip]
        end
        p[i] = artificial_viscosity_c!(rcell,zcell,ucell,vcell,ρ[i],p[i])
    end
    
        return p
        
    end       

artificial_viscosity! (generic function with 1 method)

In [30]:
function l_viscosity(x,y,α)
    xc = sum(x)/4; yc = sum(y)/4
    d = zeros(Float64,4)
    for i in 1:4
    d[i] = distance(x[i],y[i],xc,yc,α)
    end
    A = A_z(x, y)
    L = 2sum(A)/sum(d)
    return L
end

l_viscosity (generic function with 1 method)

#### distance from  Point to line 
Line: $$ (xc -cos \alpha )(x-xc) = (yc-sin \alpha)(y-yc)$$
point: $x,y$

In [31]:
function distance(x,y,xc,yc,α)
    d = abs((xc - cosd(α)) * (x .-xc)- (yc-sind(α))*(y .- yc))/√((xc-cosd(α))^2+(yc-sind(α))^2)
    return d
end

distance (generic function with 1 method)

### 沙漏粘性 Hourglass

$$ \text{hg}_x = u_1 -u_2 + u_3 - u_4$$ 
$$ \text{hg}_x = v_1 -v_2 + v_3 - v_4$$ 

$$ e_{1x} = -\frac{1}{4}q\rho c\sqrt{A}\text{hg}_x $$
$$ e_{1y} = -\frac{1}{4}q\rho c\sqrt{A}\text{hg}_y $$

$$ e_{2x} = \frac{1}{4}q\rho c\sqrt{A}\text{hg}_x $$
$$ e_{2y} = \frac{1}{4}q\rho c\sqrt{A}\text{hg}_y $$

$$ e_{3x} = -\frac{1}{4}q\rho c\sqrt{A}\text{hg}_x $$
$$ e_{3y} = -\frac{1}{4}q\rho c\sqrt{A}\text{hg}_y $$

$$ e_{4x} = \frac{1}{4}q\rho c\sqrt{A}\text{hg}_x $$
$$ e_{4y} = \frac{1}{4}q\rho c\sqrt{A}\text{hg}_y $$

In [32]:
function hourglass_viscosity(x,y,u,v,ρ,p,σ)
    hgx = u[1] - u[2] + u[3] -u[4]
    hgy = v[1] - v[2] + v[3] -v[4]
    
    ex =zeros(Float64,4)
    ey =zeros(Float64,4)
    A = area_quadrangle(x,y)
    c = sound([ρ,0.0,p,min(p+σ[1],p+σ[2])], con1)
 #   @show c
    q = 0.6 # coefficient of hourglass viscosity 0.01 - 0.5 ?
    ex[1] = -0.25q*ρ*c*√(A)*hgx
    ey[1] = -0.25q*ρ*c*√(A)*hgy
    
    ex[2] = -ex[1]
    ey[2] = -ey[1]
    
    ex[3] = ex[1]
    ey[3] = ey[1]
    
    ex[4] = ex[2]
    ey[4] = ey[2]
    
 #  ex .= 0
#    ey .= 0
 #   @show ex,ey
    return ex, ey
end

hourglass_viscosity (generic function with 1 method)

In [33]:
function area_quadrangle(x::Array{Float64,1},y::Array{Float64,1}) 
   
    xc= sum(x[i] for i in 1:4)/4
    yc= sum(y[i] for i in 1:4)/4
    
    A41 = Area3(x[4],x[1],xc,y[4],y[1],yc)
    A12 = Area3(x[1],x[2],xc,y[1],y[2],yc)
    A23 = Area3(x[2],x[3],xc,y[2],y[3],yc)
    A34 = Area3(x[3],x[4],xc,y[3],y[4],yc)
    
    A = A12 + A23 +A34 +A41
    return A
end

area_quadrangle (generic function with 1 method)

In [34]:
function Area3(x1,x2,x3,y1,y2,y3)
    return abs((x1*y2+y1*x3+x2*y3-x1*y3-y1*x2-y2*x3)/2)
end

Area3 (generic function with 1 method)

###  $\frac{\partial (u,v)}{\partial (x,y)}$

we use the diffences between 1 and 3 points and 2 and 4 points to solve the partial differences approximately, as
$$ \frac{\partial u}{\partial x}  \approx \frac{1}{2A}((u_1-u_3)(y_2-y_4)+(u_2-u_4)(-y_1+y_3))$$ 

$$ \frac{\partial v}{\partial y}  \approx -\frac{1}{2A}((v_1-v_3)(x_2-x_4)+(v_2-v_4)(-x_1+x_3))$$ 
Similar process to $\frac{\partial u}{\partial y}$,$\frac{\partial v}{\partial x}$ and $\frac{\partial v}{\partial y}$

In [35]:
function ∂uv(x,y,u)
    ∂u_∂x = 0.5(u[1]-u[3])*(y[2]-y[4]) + 0.5(u[2]-u[4])*(y[3]-y[1])
    ∂u_∂y = -0.5(u[1]-u[3])*(x[2]-x[4]) - 0.5(u[2]-u[4])*(x[3]-x[1])
    return ∂u_∂x,∂u_∂y
end

∂uv (generic function with 1 method)

## Output function

In [36]:
function cell_coordinate(x,y)
    Ip, = size(Tc)
    Ic, = size(Tp)
    xc = zeros(Float64,Ic)
    yc = zeros(Float64,Ic)
    
    for i in 1:Ic
        for j = 1:4
            ip = Tp[i,j] 
            xc[i] += x[ip]/4
            yc[i] += y[ip]/4
        end
        
    end
    
    return xc,yc
end

cell_coordinate (generic function with 1 method)

In [37]:
function outputline(Ix,Iy,var,mz)
    r,z,u,v,ρ,p,σ = var.r,var.z,var.u,var.v,var.ρ,var.p,var.σ
    I, = size(ρ)
    
    uline =  zeros(Float64,Ix)
    rline =  zeros(Float64,Ix)
    zline =  zeros(Float64,Ix)
    ρline =  zeros(Float64,Ix)        
    pline =  zeros(Float64,Ix)  
    sline = zeros(Float64,Ix,3)
    σline= zeros(Float64,Ix,3)
    for i in 1:Ix
        j = Int(floor(Iy/2))
            ip = i+(j-1 ) *(Ix+1)
            ic =i+(j-1)*Ix
            uline[i] = u[ip]
            rline[i]  = r[ip]
            ρline[i]  = ρ[ic]
            pline[i] = p[ic]
            σline[i,:] .= σ[ic,:]
            sline[i,1:2] .= σ[ic,1:2] .+ p[ic]
            sline[i,3]=σ[i,3]
    end
    return rline,uline,ρline,pline,sline,σline
end

outputline (generic function with 1 method)

In [38]:
function Output_cell(Ix,Iy,var,mz)
    x,y,u,v,ρ,p,σ = var.r,var.z,var.u,var.v,var.ρ,var.p,var.σ
    Ip, = size(Tc)
    Ic, = size(Tp)
    io = open("data.dat", "w+")
   
    A = zeros(Float64,Ip,9)
   # for i in 1:Ip
    
    text = " TITLE = \"Dataset\"
VARIABLES = \"x\" \"y\" \"u\" \"v\" \"rho\" \"p\" \"srr\" \"szz\" \"mz\" ZONE T=\"Zone 1\" 
I=$Ix,J=$Iy,K=1,ZONETYPE=Ordered 
DATAPACKING=POINT \n "
  #  write(1,*)
    write(io,text)

    for i in 1:Ic
        xc = 0
        yc =0
        uc =0
        vc =0
        for j = 1:4
            ip = Tp[i,j] 
                xc += x[ip]/4
                yc += y[ip]/4
                uc += u[ip]/4
                vc += v[ip]/4
        
        end
        
        A[i,1] = xc
        A[i,2] = yc
        A[i,3] = uc
        A[i,4] = vc
        A[i,5] = ρ[i]
        A[i,6] = p[i]
        A[i,7] = σ[i,1] + p[i]
        A[i,8] = σ[i,2] +p[i]
        A[i,9] = mz[i]
        
    end
      writedlm(io, A, "  ")
    close(io)
end

Output_cell (generic function with 1 method)

## Cases

In [39]:
 function Piston()

    global problem = prb(1.5e-4,0.3)
    # global problem = prb(3e-5,0.3)
     
    I = 200
    J = 10
    dx = 1.0/I
    dy = 0.1/J
    
    global   con1 = Const(9e7,8930,2.0,4.5e10,3940.0,1.49)
  #  global   con1 = Const(0.0,8930,2.0,4.5e10,3940.0,1.49)
    Ip = (I+1)*(J+1) # Number of  points
    Ic = I*J  # number of cells
    
    global Tp = zeros(Int,Ic,4) #格点
    global Tc = zeros(Int,Ip,4) #点格
    
    #@show Tc, Ip
    global Tb = zeros(Int, I*2+J*2,3) #边界 
    
    IBL = J+1
    IBR = J+1
    IBU = I+1
    IBD = I+1
   # 点格表，格点表初始化 
    for i in 1:I 
        for j in 1:J
            ic = i+(j-1)*I
            Tp[ic,1] = i + (j-1)*(I+1)
            Tp[ic,2] = i+1 +(j-1)*(I+1)
            Tp[ic,3]=i+1+j*(I+1)
            Tp[ic,4]=i+j*(I+1) 
        end
    end
    
    for i = 1:I+1
        for j = 1:J+1
            ip = i+(j-1)*(I+1)
            Tc[ip,1] = i +(j-1)*I #(i,j)
            Tc[ip,2] = i-1+(j-1)*I #(i-1,j)
            Tc[ip,3] = i-1+(j-2)*I #(i-1,j-1)
            Tc[ip,4] = i+(j-2)*I   #(i,j-1)
            end
        end
    

# Bound 
  ib = 0
    for i = 1:I+1
        for j = 1:J+1
            if i == 1 || i== I+1 ||  j == 1 || j == J+1
                ib += 1
                ic =i+(j-1)*I 
                Tb[ib,1] = ip
                if i==1 
                    Tb[ib,2] = 4
                    Tb[ip,3] = 3
                end   
                 if  i==I+1 
                    Tb[ib,3] = 2 #bound type 1:free 2: wall ..  Tb[:,2] y direction
                    Tc[ip,1] =0
                    Tc[ip,4] =0
                end
            
                if j==1 
                    Tb[ib,2] = 1
                    Tc[ip,3] = 0
                    Tc[ip,4] = 0
                end
                if j==J+1
                    Tb[ib,2] = 1
                    Tc[ip,1] = 0
                    Tc[ip,2] = 0
                end
            end
        end
    end

    #流场初始化 Init of the flow
    
    x = zeros(Float64,Ip)
    y = zeros(Float64,Ip)
    u = zeros(Float64,Ip)
    v = zeros(Float64,Ip)
    
    ρ = zeros(Float64,Ic)
    mz = zeros(Float64,Ic)
    p = zeros(Float64,Ic)
    Az= zeros(Float64,Ic)
    σ = zeros(Float64,Ic,3)
    
    for i in 1:I+1
        for j = 1:J+1
            ip =i+(j-1)*(I+1)
            x[ip] = (i-1)*dx
            y[ip] = (j-1)*dy
            if i >=I/2
                u[ip] = 0.
            else
                u[ip] = 0
            end
            v[ip] = 0.0
        end
    end
    
    xz = zeros(Float64,4)
    yz = zeros(Float64,4) 
    for i in 1:I
        for j in 1:J
            ic = i+(j-1)*I
            xz[1:4] = x[Tp[ic,1:4]]
            yz[1:4] = y[Tp[ic,1:4]]
            A = A_z(xz,yz)
            Az[ic] = sum(A) #[1]+A[2]+A[3]+A[4]
          #  if i>=I/2
               
                p[ic] = 1.e5
                ρ[ic] = 8930
                mz[ic] = ρ[ic] * Az[ic]
                σ[ic,1] = -p[ic]
                σ[ic,2] = -p[ic]
                σ[ic,3]= 0 
#             else
#                 mz[ic] = 1.0 * Az[ic]
#                 p[ic] = 1.0
#                 ρ[ic] = 1.0
#             end
        end
    end
    var = Var(x,y,u,v,ρ,p,σ)
    return var,mz,I,J
end

Piston (generic function with 1 method)

In [40]:
var,mz,I,J=Piston()
#Output1
var = TimeSolve(var,mz)

UndefVarError: UndefVarError: y not defined

In [5]:
using PyPlot

In [2]:
push!(LOAD_PATH,"/home/bfly/workspace/Juliastudy/Src")

4-element Array{String,1}:
 "@"                                  
 "@v#.#"                              
 "@stdlib"                            
 "/home/bfly/workspace/Juliastudy/Src"

In [3]:
using Lag1DNum

┌ Info: Recompiling stale cache file /home/bfly/.juliapro/JuliaPro_v1.1.1.1/compiled/v1.1/Lag1DNum.ji for Lag1DNum [top-level]
└ @ Base loading.jl:1184


In [4]:
uo,u,x,inter = Lag1DNum.Piston()
uo,x  = Lag1DNum.TimeSolve(uo, x,inter)

3.180526342855994e-7  3.180526342855994e-7
3.180264183352437e-7  6.360790526208431e-7
3.1796314542188546e-7  9.540421980427286e-7
3.1787373431572483e-7  1.2719159323584536e-6
3.177612408329017e-7  1.5896771731913552e-6
3.1764099208808404e-7  1.9073181652794392e-6
3.1751012713946967e-7  2.224828292418909e-6
3.1737632129201164e-7  2.5422046137109208e-6
3.172460196713848e-7  2.8594506333823056e-6
3.17129074630918e-7  3.1765797080132238e-6
3.17024269231959e-7  3.493603977245183e-6
3.169314332081582e-7  3.810535410453341e-6
3.16851916540164e-7  4.127387326993505e-6
3.167880103080494e-7  4.444175337301554e-6
3.167378873171647e-7  4.760913224618719e-6
3.16698395164153e-7  5.077611619782872e-6
3.166661892092715e-7  5.394277808992143e-6
3.16638342092012e-7  5.710916151084156e-6
3.166130239284036e-7  6.02752917501256e-6
3.1658949836891756e-7  6.344118673381478e-6
3.165679206893685e-7  6.660686594070846e-6
3.1654928858314176e-7  6.977235882653988e-6
3.1653383123296457e-7  7.293769713886952e-6
3.1

3.1651197594477275e-7  9.433464148802472e-5
3.1651196760102764e-7  9.465115345562576e-5
3.165119610784227e-7  9.496766541670417e-5
3.165119500364571e-7  9.528417736674063e-5
3.165119335466083e-7  9.560068930028724e-5
3.165119184642271e-7  9.591720121875147e-5
3.165119056058458e-7  9.623371312435732e-5
3.165118953935306e-7  9.655022501975085e-5
3.165118882419564e-7  9.686673690799281e-5
3.165118843969105e-7  9.718324879238972e-5
3.1651188345192714e-7  9.749976067584165e-5
3.1651188513841824e-7  9.781627256098007e-5
3.16511889181023e-7  9.81327844501611e-5
3.16511895249664e-7  9.844929634541075e-5
3.1651190321935336e-7  9.876580824863011e-5
3.16511913176465e-7  9.908232016180658e-5
3.1651192411612966e-7  9.93988320859227e-5
3.1651193513310233e-7  9.971534402105581e-5
3.165119374667682e-7  0.00010003185595852259
3.1651193840201614e-7  0.0001003483678969246
3.1651194173314923e-7  0.00010066487983865775
3.1651194826453463e-7  0.00010098139178692228
3.1651195836161597e-7  0.00010129790374528

([8973.42 20.0 6.82542e8 -5.91304e7; 8973.42 20.0 6.82542e8 -5.91304e7; … ; 8930.0 -6.00601e-13 100000.0 -0.00307235; 8930.0 -6.24381e-13 100000.0 0.00615788], [-0.0119797, -0.00699711, -0.00201452, 0.00296129, 0.00793707, 0.0129129, 0.0178886, 0.0228644, 0.0278402, 0.032816  …  0.97, 0.975, 0.98, 0.985, 0.99, 0.995, 1.0, 1.005, 1.01, 1.015])

In [100]:
#plot(x,uo[:,4])
plot(rline,sline[:,1])

1-element Array{PyCall.PyObject,1}:
 PyObject <matplotlib.lines.Line2D object at 0x7f0024f871d0>

In [37]:
rcell, zcell = cell_coordinate(var.r,var.z)

([0.00548787, 0.0104636, 0.0154393, 0.020415, 0.0253907, 0.0303664, 0.0353422, 0.040318, 0.0452938, 0.0502696  …  0.9525, 0.9575, 0.9625, 0.9675, 0.9725, 0.9775, 0.9825, 0.9875, 0.9925, 0.9975], [0.00496078, 0.00492459, 0.00496417, 0.00504453, 0.00511843, 0.00516353, 0.00518388, 0.00519064, 0.00519236, 0.00519261  …  0.095, 0.095, 0.095, 0.095, 0.095, 0.095, 0.095, 0.095, 0.095, 0.095])

In [382]:
var.σ[:,2] .+var.p[:]

4000-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [96]:
rline,uline,ρline,pline,sline,σline = outputline(I, J, var, mz)

([0.003, 0.0079755, 0.0129505, 0.0179258, 0.0229011, 0.0278765, 0.0328519, 0.0378272, 0.0428026, 0.047778  …  0.95, 0.955, 0.96, 0.965, 0.97, 0.975, 0.98, 0.985, 0.99, 0.995], [20.0, 20.0052, 19.9953, 19.9939, 19.9944, 19.9938, 19.9946, 19.9945, 19.9946, 19.9948  …  -7.24954e-9, -3.3394e-9, -3.30875e-10, -1.91651e-9, -1.65644e-9, -5.41445e-9, -2.03663e-9, -2.64075e-9, -6.11685e-9, -2.2862e-9], [8973.97, 8974.87, 8974.41, 8974.23, 8974.24, 8974.17, 8974.21, 8974.2, 8974.19, 8974.2  …  8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0], [6.96974e8, 6.98105e8, 6.95231e8, 6.94067e8, 6.93942e8, 6.93707e8, 6.93686e8, 6.93644e8, 6.93608e8, 6.93595e8  …  1.00002e5, 100003.0, 99999.5, 99999.9, 99999.0, 1.00001e5, 99999.9, 99999.1, 1.00001e5, 1.00001e5], [-3.14732e7 2.49999e7 -3.271e7; -3.02146e7 2.10528e7 -4.45125e7; … ; 1.08554 -1.37866 -0.296824; 0.608032 -0.767777 -0.203145], [-7.28447e8 -6.71974e8 -3.271e7; -7.2832e8 -6.77052e8 -4.45125e7; … ; -1.0e5 -1.00003e5 

In [433]:
plot(rline1,ρline1)
plot(rline,ρline)

1-element Array{PyCall.PyObject,1}:
 PyObject <matplotlib.lines.Line2D object at 0x7f649ebe5da0>

In [427]:

rline1 = copy(rline)
ρline1 = copy(ρline)

500-element Array{Float64,1}:
 8973.452548068302
 8973.489348740997
 8973.529132466845
 8973.546156105233
 8973.593873162596
 8973.652536475118
 8973.658593989336
 8973.611523470208
 8973.548061198695
 8973.496301843043
 8973.468327046758
 8973.457481706046
 8973.453148756262
    ⋮             
 8930.00000074822 
 8929.999996725186
 8930.000001110711
 8929.999999780026
 8929.999999121655
 8930.000002731076
 8929.999998861405
 8929.999997659297
 8930.00000244914 
 8930.00000029278 
 8929.999998062065
 8929.999999677786

In [426]:
using Plots

In [120]:
A = rand(Float64,100)

100-element Array{Float64,1}:
 0.5863745424229245  
 0.43464244640415384 
 0.3910598594800654  
 0.43305240022454616 
 0.23399114758541195 
 0.18927979722780974 
 0.0399318765583454  
 0.8247603605119291  
 0.8450500969105932  
 0.8685808529175953  
 0.9115293391579375  
 0.4151161129201457  
 0.8434724475699895  
 ⋮                   
 0.5549218857722769  
 0.8509211097763569  
 0.7911310905976383  
 0.683086936974606   
 0.04829929770646024 
 0.2695140134177052  
 0.6730876715858984  
 0.04185936225327502 
 0.4647567613578325  
 0.5453259625191897  
 0.030370869037166237
 0.9109183444891766  

In [171]:
 function Pistonz()

    global problem = prb(1.5e-4,0.3)
    # global problem = prb(3e-5,0.3)
     
    I = 10
    J = 100
    dx = 0.1/I
    dy = 1/J
    
    global   con1 = Const(9e7,8930,2.0,4.5e10,3940.0,1.49)
    
    Ip = (I+1)*(J+1) # Number of  points
    Ic = I*J  # number of cells
    
    global Tp = zeros(Int,Ic,4) #格点
    global Tc = zeros(Int,Ip,4) #点格
    
    #@show Tc, Ip
    global Tb = zeros(Int, I*2+J*2,3) #边界 
    
    IBL = J+1
    IBR = J+1
    IBU = I+1
    IBD = I+1
   # 点格表，格点表初始化 
    for i in 1:I 
        for j in 1:J
            ic = i+(j-1)*I
            Tp[ic,1] = i + (j-1)*(I+1)
            Tp[ic,2] = i+1 +(j-1)*(I+1)
            Tp[ic,3]=i+1+j*(I+1)
            Tp[ic,4]=i+j*(I+1) 
        end
    end
    
    for i = 1:I+1
        for j = 1:J+1
            ip = i+(j-1)*(I+1)
            Tc[ip,1] = i +(j-1)*I #(i,j)
            Tc[ip,2] = i-1+(j-1)*I #(i-1,j)
            Tc[ip,3] = i-1+(j-2)*I #(i-1,j-1)
            Tc[ip,4] = i+(j-2)*I   #(i,j-1)
            end
        end
    

# Bound 
  ib = 0
    for i = 1:I+1
        for j = 1:J+1
            if i == 1 || i== I+1 ||  j == 1 || j == J+1
                ib += 1
                ic =i+(j-1)*I
                #ic = Tc[ip]
                Tb[ib,1] = ic
                if i==1 
                    Tb[ib,2] = 4 # 1->4 
                    Tb[ib,3] = 2 # type 1:free 2:
                end   
                 if  i==I+1 
                    Tb[ib,2] = 2 #bound type 1:free 2: wall ..  Tb[:,2] y direction
                    Tb[ib,3] = 2
                end
            
                if j==1 
                    Tb[ib,2] = 1
                    Tb[ib,3] = 1
                end
                if j==J+1
                    Tb[ib,2] = 3 
                    Tb[ib,3] = 1
                end
            end
        end
    end

    #流场初始化 Init of the flow
    
    x = zeros(Float64,Ip)
    y = zeros(Float64,Ip)
    u = zeros(Float64,Ip)
    v = zeros(Float64,Ip)
    
    ρ = zeros(Float64,Ic)
    mz = zeros(Float64,Ic)
    p = zeros(Float64,Ic)
    Az= zeros(Float64,Ic)
    σ = zeros(Float64,Ic,3)
    
    for i in 1:I+1
        for j = 1:J+1
            ip =i+(j-1)*(I+1)
            x[ip] = (i-1)*dx
            y[ip] = (j-1)*dy
            u[ip] = 0
            v[ip] = 0.0
        end
    end
    
    xz = zeros(Float64,4)
    yz = zeros(Float64,4) 
    for i in 1:I
        for j in 1:J
            ic = i+(j-1)*I
            xz[1:4] = x[Tp[ic,1:4]]
            yz[1:4] = y[Tp[ic,1:4]]
            A = A_z(xz,yz)
            Az[ic] = sum(A) #[1]+A[2]+A[3]+A[4]
          #  if i>=I/2
               
                p[ic] = 1.e5
                ρ[ic] = 8930
                mz[ic] = ρ[ic] * Az[ic]
                σ[ic,1] = -p[ic]
                σ[ic,2] = -p[ic]
                σ[ic,3]= 0 
#             else
#                 mz[ic] = 1.0 * Az[ic]
#                 p[ic] = 1.0
#                 ρ[ic] = 1.0
#             end
        end
    end
    var = Var(x,y,u,v,ρ,p,σ)
    return var,mz,I,J
end

Pistonz (generic function with 1 method)

In [80]:
var,mz,I,J=Pistonz()
#Output1
var = TimeSolve(var,mz)

1.89753273733184e-6
3.1539342762764637e-6
5.0338827434729315e-6
6.286262815781695e-6
7.538634185142826e-6
9.417370285475579e-6
1.0669836096228317e-5
1.2548744033034222e-5
1.3801328840671643e-5
1.5053929424875505e-5
1.6932863026220495e-5
1.818550906799995e-5
2.0064458309234472e-5
2.131709333505035e-5
2.2569750378759563e-5
2.444874048473567e-5
2.5701382852252996e-5
2.7580337957709158e-5
2.8832984917209406e-5
3.0085637169156982e-5
3.196460501887529e-5
3.3217245705678165e-5
3.509621368280087e-5
3.634886432712129e-5
3.760151297808892e-5
3.948048234022316e-5
4.0733130324313886e-5
4.261210774482241e-5
4.3864757968481754e-5
4.5117405843808e-5
4.699637601564817e-5
4.82490240625757e-5
4.950167252000113e-5
5.138064371139526e-5
5.2633290220644624e-5
5.451226045856058e-5
5.5764907582727244e-5
5.701755448410242e-5
5.889652431465627e-5
6.014917091458618e-5
6.202814111643358e-5
6.328078798479191e-5
6.453343487462532e-5
6.641240547518485e-5
6.766505290408875e-5
6.95440248468682e-5
7.07966734510339e-5
7

Var([-6.41544e-21, 0.00999969, 0.0199994, 0.0299991, 0.0399989, 0.0499987, 0.0599987, 0.0699987, 0.079999, 0.0899994  …  0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1], [0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003, 0.003  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [-3.55384e-16, 0.00126263, 0.00195011, 0.00155113, 0.0021002, 0.00065951, 0.00161208, 0.00120274, 0.000158777, 0.00128656  …  5.0869e-10, -9.31551e-10, -3.57749e-9, -7.18434e-9, -1.16939e-8, -1.5029e-8, -1.62259e-8, -1.3183e-8, -5.23436e-9, -3.98691e-19], [20.0, 19.9997, 20.0006, 19.9992, 20.0008, 19.9998, 19.9988, 20.0021, 19.9986, 20.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.07832e-8], [8974.62, 8974.63, 8974.61, 8974.64, 8974.59, 8974.67, 8974.61, 8974.61, 8974.63, 8974.63  …  8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0, 8930.0], [7.00786e8, 7.00823e8, 7.00548e8, 7.01083e8, 7.00223e8, 7.01476e8, 7.00504e8, 7.00597e8, 7.00924e8, 7.00813e8  …  1.

In [81]:
rcell, zcell = cell_coordinate(var.r,var.z)

([0.00502008, 0.0150198, 0.0250196, 0.0350193, 0.0450191, 0.0550188, 0.0650186, 0.0750183, 0.085018, 0.0950177  …  0.005, 0.015, 0.025, 0.035, 0.045, 0.055, 0.065, 0.075, 0.085, 0.095], [0.00797526, 0.00797526, 0.00797528, 0.00797524, 0.00797531, 0.00797521, 0.00797531, 0.00797527, 0.00797528, 0.00797531  …  0.995, 0.995, 0.995, 0.995, 0.995, 0.995, 0.995, 0.995, 0.995, 0.995])

In [41]:
plot3D(var.r,var.z,var.v)
#triplot()

1-element Array{PyCall.PyObject,1}:
 PyObject <mpl_toolkits.mplot3d.art3d.Line3D object at 0x7f00261cc898>

In [445]:
tricontourf(var.r,var.z,var.v)

PyObject <matplotlib.tri.tricontour.TriContourSet object at 0x7f649e9f8588>

In [342]:
@show var.u

var.u = [-1.63729e-16, -0.000339231, -0.00103502, -0.00215996, -0.00209362, -1.98177e-15, -0.553513, -0.540354, -0.528083, -0.51507, -0.502981, -0.494768, -0.541396, -0.55734, -0.573565, -0.591099, -0.606775, -0.618052, 0.227948, 0.184097, 0.140541, 0.0973573, 0.0495269, -0.00416906, 1.00851, 1.03848, 1.06852, 1.09921, 1.13693, 1.18099, 1.1355, 1.10624, 1.07644, 1.04596, 1.01744, 0.990026, 1.35043, 1.34889, 1.34802, 1.34816, 1.34832, 1.34794, 1.40056, 1.39694, 1.39166, 1.38495, 1.37805, 1.37194, 1.35646, 1.3584, 1.36112, 1.36443, 1.36736, 1.36873, 1.36, 1.36162, 1.36362, 1.36527, 1.36623, 1.36619, 1.36933, 1.3708, 1.37261, 1.37375, 1.3742, 1.37466, 1.37582, 1.37728, 1.379, 1.37993, 1.38032, 1.3811, 1.38187, 1.3829, 1.38428, 1.38494, 1.38504, 1.3852, 1.38695, 1.38848, 1.39018, 1.39115, 1.39151, 1.39174, 1.3938, 1.39441, 1.39499, 1.39518, 1.39502, 1.39442, 1.39943, 1.40025, 1.4009, 1.40113, 1.40114, 1.40066, 1.40306, 1.40367, 1.40416, 1.40431, 1.40418, 1.40364, 1.4115, 1.41161, 1.41154, 

606-element Array{Float64,1}:
 -1.6372866436092676e-16
 -0.0003392307937845209 
 -0.0010350232755911197 
 -0.002159961415690488  
 -0.002093624784268034  
 -1.981769884851758e-15 
 -0.5535133193792093    
 -0.5403544097656826    
 -0.5280832664496713    
 -0.5150699134867768    
 -0.5029812338755582    
 -0.4947683706116317    
 -0.5413959943761063    
  ⋮                     
  9.444882773050668e-9  
  1.1955284996236734e-8 
  1.4404017967736131e-8 
  1.6604582287583483e-8 
  1.91830478657589e-8   
  2.168373224922474e-8  
 -7.915838847811767e-25 
 -2.2403242988536943e-10
 -4.3307702885511666e-10
 -6.915252277924711e-10 
 -9.622376800382658e-11 
 -3.423441114867148e-24 

In [71]:
? Const

search: Const const isconst MathConstants codeunits ncodeunits countlines



No documentation found.

# Summary

```
struct Const <: Any
```

# Fields

```
Y0 :: Float64
ρ0 :: Float64
Γ0 :: Float64
μ  :: Float64
a0 :: Float64
s0 :: Float64
```


In [8]:
 function Collapse()

    #global problem = prb(1.3e-4,0.3)
     global problem = prb(5e-5,0.3)
    
    I = 40
    J = 32
    dr = 0.02/J
    dθ = 90/I
    
    global   con1 = Const(3.3e8,1848,2.0,1.519e11,1.287e4,1.124)
    
    Ip = (I+1)*(J+1) # Number of  points
    Ic = I*J  # number of cells
    
    global Tp = zeros(Int,Ic,4) #格点
    global Tc = zeros(Int,Ip,4) #点格
    
    #@show Tc, Ip
    global Tb = zeros(Int, I*2+J*2,3) #边界 
    
    IBL = J+1
    IBR = J+1
    IBU = I+1
    IBD = I+1
   # 点格表，格点表初始化 
    for i in 1:I 
        for j in 1:J
            ic = i+(j-1)*I
            Tp[ic,1] = i + (j-1)*(I+1)
            Tp[ic,2] = i+1 +(j-1)*(I+1)
            Tp[ic,3]=i+1+j*(I+1)
            Tp[ic,4]=i+j*(I+1) 
        end
    end
    
    for i = 1:I+1
        for j = 1:J+1
            ip = i+(j-1)*(I+1)
            Tc[ip,1] = i +(j-1)*I #(i,j)
            Tc[ip,2] = i-1+(j-1)*I #(i-1,j)
            Tc[ip,3] = i-1+(j-2)*I #(i-1,j-1)
            Tc[ip,4] = i+(j-2)*I   #(i,j-1)
            end
        end
    

# Bound 
  ib = 0
    for i = 1:I+1
        for j = 1:J+1
            if i == 1 || i== I+1 ||  j == 1 || j == J+1
                ib += 1
                ic =i+(j-1)*(I) 
                Tb[ib,1] = ic
                if i==1 
                    Tb[ib,2] = 1
                    Tb[ib,3] = 2
                end   
                 if  i==I+1 
                    Tb[ib,2] = 2 #bound type 1:free 2: wall ..  Tb[:,2] y direction
                    Tb[ib,3] = 2
                end
            
                if j==1 
                    Tb[ib,2] = 1
                    Tc[ip,3] = 0
                    Tc[ip,4] = 0
                end
                if j==J+1
                    Tb[ib,2] = 1
                    Tc[ip,1] = 0
                    Tc[ip,2] = 0
                end
            end
        end
    end

    #流场初始化 Init of the flow
    
    x = zeros(Float64,Ip)
    y = zeros(Float64,Ip)
    u = zeros(Float64,Ip)
    v = zeros(Float64,Ip)
    
    ρ = zeros(Float64,Ic)
    mz = zeros(Float64,Ic)
    p = zeros(Float64,Ic)
    Az= zeros(Float64,Ic)
    σ = zeros(Float64,Ic,3)
    
    for i in 1:I+1
        for j = 1:J+1
            ip =i+(j-1)*(I+1)
            r₁ = (j-1)*dr+0.08
            θ = 90-(i-1)*dθ
            v₀ = 417.1
            x[ip] = cosd(θ)*r₁
            y[ip] = sind(θ)*r₁
            u[ip] = -v₀*0.08/r₁ *cosd(θ)
            v[ip] = -v₀*0.08/r₁ *sind(θ)
        end
    end
    
    xz = zeros(Float64,4)
    yz = zeros(Float64,4) 
    for i in 1:I
        for j in 1:J
            ic = i+(j-1)*I
            xz[1:4] = x[Tp[ic,1:4]]
            yz[1:4] = y[Tp[ic,1:4]]
            A = A_z(xz,yz)
            Az[ic] = sum(A) #[1]+A[2]+A[3]+A[4]
          #  if i>=I/2
               
                p[ic] = 1.e5
                ρ[ic] = 1848.0
                mz[ic] = ρ[ic] * Az[ic]
                σ[ic,1] = -p[ic]
                σ[ic,2] = -p[ic]
                σ[ic,3]= 0 
#             else
#                 mz[ic] = 1.0 * Az[ic]
#                 p[ic] = 1.0
#                 ρ[ic] = 1.0
#             end
        end
    end
    var = Var(x,y,u,v,ρ,p,σ)
    return var,mz,I,J
end

Collapse (generic function with 1 method)

In [170]:
var,mz,I,J = Collapse()
var = TimeSolve(var,mz)

5.069872948337846e-7
1.0029394211623647e-6
1.509907916691257e-6
2.0058242801253917e-6
2.5016921991587406e-6
3.008512897607421e-6
3.50422481237224e-6
4.010841151022723e-6
4.506350899653295e-6
5.001763569430248e-6
5.5080827698895975e-6
6.003279637219993e-6
6.509344029356328e-6
7.004246113482291e-6
7.509969962228995e-6
8.004541726252994e-6
8.510009981535977e-6
9.004448770672106e-6
9.509760557333868e-6
1.0003888181766958e-5
1.0508777551455481e-5
1.1002508862369548e-5
1.1506957152299452e-5
1.2000197300852373e-5
1.2504204377456656e-5
1.30079828826561e-5
1.3500510609729618e-5
1.4003635674692461e-5
1.4506444969505339e-5
1.500893487707457e-5
1.550022318176145e-5
1.600217657559493e-5
1.6503894250449706e-5
1.7005306111726296e-5
1.750635229184465e-5
1.8006070456101768e-5
1.850443690392119e-5
1.9001555316566724e-5
1.9508554945181923e-5
2.0004289336963134e-5
2.0510377520719836e-5
2.1004705670466076e-5
2.1508247389081566e-5
2.2010180502734593e-5
2.2510485137956666e-5
2.3009134217942657e-5
2.350629497

DomainError: DomainError with -3.537735264589223e7:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [159]:
#scatter(var.r,var.z)
triplot(var.r,var.z)

2-element Array{PyCall.PyObject,1}:
 PyObject <matplotlib.lines.Line2D object at 0x7f00264988d0>
 PyObject <matplotlib.lines.Line2D object at 0x7f0026498cc0>

In [64]:
var.r,var.z

([0.08, 0.0799383, 0.0797534, 0.0794455, 0.0790151, 0.0784628, 0.0777896, 0.0769964, 0.0760845, 0.0750553  …  0.0346117, 0.0309017, 0.027144, 0.0233445, 0.019509, 0.0156434, 0.0117537, 0.00784591, 0.00392598, 0.0], [0.0, 0.00314079, 0.00627673, 0.00940299, 0.0125148, 0.0156072, 0.0186756, 0.0217152, 0.0247214, 0.0276894  …  0.0938191, 0.0951057, 0.0962455, 0.097237, 0.0980785, 0.0987688, 0.0993068, 0.0996917, 0.0999229, 0.1])

In [168]:
using DelimitedFiles
Output_cell(I,J,var,mz)

In [155]:
sind(90)

1.0

In [2]:
A = zeros(Float64,3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [4]:
A[end]

0.0

In [6]:
for i in (1,3)
    println(i)
end

1
3
